[package]
name = "micro_scanner"
version = "0.1.0"
authors = ["jp6ru8958958 <jp6ru8958958@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "micro_scanner"
path = "src/main.rs"
